### ISSUE TITLE
Review about the initial release v0.0.2

### ISSUE THREAD

**Issue by xmoroccan** [OpenIMW/laravel-seo#1]
### First thanks for the efforts, I really appreciate that a lot.

I've tried to figure out how things work, so my review may not be accurate (cuz it's based on my thoughts).

I like the idea of extending the abstract class for each view but in my point of view this more classes to maintain, what I'm thinking is we should maintain this on simple config file if we want to _(maybe it's not accomplished with my approach, so correct me if I'm wrong)_

I'll try to write some pseudo-code to demonstrate how I see the package

```php
// config/meta-tags.php
return [
  App\Models\Product => [
    'title' => ['title', 'og:title', 'twitter:title'],
    'description' => ['description', 'og:description', 'twitter:description'],
    // Here we can use a method if we want from the class
    // In this case `App\Models\Product`
    'getImage' => ['image', 'og:image']
  ]
]
```

in this time when I'm writing these lines, I figure that my idea has some limitation, I think we should use tag names as the array keys delimited with `|` like the validation rules notation, so the instead:
```php
// config/meta-tags.php
return [
  App\Models\Product => [
    'title|og:title|twitter:title' => 'title',
    'description|og:description|twitter:description' => 'description',
    // Here we can use a method if we want from the class
    // In this case `App\Models\Product`
    'image|og:image' => 'getImage'
  ],
  // We also can use general rule for example
  'home' => [
     // Since we're in config file this can be cached
     'title' => env('app.name'),
     'description' => env('app.description')
  ]
]
```

This we'll give us the ability to use value from helpers methods too like `env()`

Then in any blade view we can use something like this:
```blade
@meta($product)
```

this under the hood well generate the tags defined in the config, don't forget that we can use the method `getImage()` from the model _(or any object)_

Imagine this scenario we have a Book model with an author related loaded model we can write the config as follows for the Book model that will be rendered on some `book.blade.php`

```php
// config/meta-tags.php
return [
  App\Book=> [
    'title|og:title|twitter:title' => 'title',
    'description|og:description|twitter:description' => 'description',
    'image|og:image' => 'getBookCover',
    'schema' => [
      'type' => 'book',
      'title' => 'title',
      ...
  ],
```
So we can also personalize the schema based on the Object or/and Model.

Besides that, here is some other notes (I know this the first release, maybe you're planned to do it later):
* Split the meta tags renderer from the sitemap generator _We need to focus on small portions of the code as small as we can_
* config to `src` folder since it's a part from the package
* require `Illuminate/support`
* some comments especially methods params
* some tests!
* Don't require your package (nothing personally here) just we don't want to jump between two repos to figure out what's going on and we need to maintain the code here, move the code to this package if you really want to re-use it

Maybe I should start a new repo just to demonstrate my idea about the meta tags renderer, maybe there are some cases that you can see but I can't see them, so let me start a simple repo and tell me what you think

Regards bruh.

**Comment by melbahja** [comment]
I think this syntax is more easy `'title|og:title|twitter:title' => 'title'`, I will see how implement this.

**Comment by xmoroccan** [comment]
We'll have one more problem with this notation, we can't know if `=> 'title'` is class property/method or just a string, one way we can do it is to fallback to string if no property or method exists, but maybe we'll have another problem if we just want a string and it exists as property we'll never get the string, any thoughts on this? 
cc @melbahja

**Comment by melbahja** [comment]
By defaults it's fallback to string, second problem maybe add space or we can add backslash`'\title'` to use string instead of property.

**Comment by xmoroccan** [comment]
Ah that's what I'm thinking some convention to skip, BTW good work bruh on the latest change kudos :raised_hands:

Let me close this issue, we'll open new one for the notation prblem
